In [1]:
import numpy as np


In [3]:
np.genfromtxt("chipotle.tsv",delimiter="\t")

array([[      nan,       nan,       nan,       nan,       nan],
       [1.000e+00, 1.000e+00,       nan,       nan,       nan],
       [1.000e+00, 1.000e+00,       nan,       nan,       nan],
       ...,
       [1.834e+03, 1.000e+00,       nan,       nan,       nan],
       [1.834e+03, 1.000e+00,       nan,       nan,       nan],
       [1.834e+03, 1.000e+00,       nan,       nan,       nan]])

In [4]:
#tạo mảng,mảng sẽ có kiểu dữ liệu ndarray
c=np.array([1,3,5])
print(c)
type(c)

[1 3 5]


numpy.ndarray

In [5]:
# Tạo 3x5 array chứa full 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
#Tạo 1 mảng gồm các giá trị ngẫu nhiên tuân theo phân phối chuẩn với mean và std đã biết
rand=np.random.normal(1,1,(3,3))

In [7]:
#trả về kích thước của mảng
rand.shape

(3, 3)

In [8]:
#Ghép 2 mảng
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [9]:
#Tính tổng,giá trị trung bình,độ lệch chuẩn của mảng
a=np.array([2,4,6,6,5])
print(a.sum(),a.mean(),a.std())

23 4.6 1.4966629547095764


In [29]:
#sắp xếp lại mảng
np.sort(a)

array([2, 4, 5, 6, 6])

In [30]:
# nhân 2 ma trận
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])